/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_HelloWorld
#define _Included_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorld
 * Method:    helloFromC
 * Signature: ()V
 */

JNIEXPORT jstring JNICALL Java_HelloWorld_helloFromC
   (JNIEnv *env, jobject obj) {

#ifdef __cplusplus
}
#endif
#endif
