
public enum QueryType {
	LOCATION_SRC_DST_FORMAT_SRC_DST,
	
	LOCATION_SRC_DST_FORMAT_SRC,
	LOCATION_SRC_DST_FORMAT_DST,
	LOCATION_SRC_FORMAT_SRC_DST,
	LOCATION_DST_FORMAT_SRC_DST,
	
	LOCATION_SRC_DST,
	LOCATION_SRC_FORMAT_SRC,
	LOCATION_SRC_FORMAT_DST,
	LOCATION_DST_FORMAT_SRC,
	LOCATION_DST_FORMAT_DST,
	FORMAT_SRC_DST,
	
	LOCATION_SRC,
	LOCATION_DST,
	FORMAT_SRC,
	FORMAT_DST,
	
	COST,
	ADVERTISEMENT_ID,
	SERVICE_NAME
}
